# Generated by Django 4.1.3 on 2022-12-16 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleo', models.CharField(choices=[('General', 'General'), ('Coronel', 'Coronel'), ('Teniente Coronel', 'Teniente Coronel'), ('Comandante', 'Comandante'), ('Capitán', 'Capitán'), ('Teniente', 'Teniente'), ('Subteniente', 'Subteniente'), ('Brigada', 'Brigada'), ('Sargento 1º', 'Sargento 1º'), ('Sargento', 'Sargento'), ('Cabo Mayor', 'Cabo Mayor'), ('Cabo 1º', 'Cabo 1º'), ('Cabo', 'Cabo'), ('Guardia Civil', 'Guardia Civil')], max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('fecha_incorporacion', models.DateField()),
                ('fotografia', models.ImageField(upload_to='')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalJAES.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Negociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negociado', models.CharField(max_length=255)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalJAES.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalJAES.unidad'),
        ),
    ]
