# Generated by Django 4.1.6 on 2023-02-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalJAES', '0002_persona_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fotografia',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
